tickers:
  - BTC
  - ETH
  - BNB
  - XRP
  - ADA
  - DOGE
  - SOL
  - DOT

strategies:
  BTC:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
  ETH:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
  BNB:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
  XRP:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
  ADA:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
  DOGE:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
  SOL:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
  DOT:
    name: "RSIStrategy"
    params:
      rsi_length: 14
      rsi_buy: 30
      rsi_sell: 70
